superuser: null
# commented until <walletAmount> gets a class getter
#welcomeMessage:
<<<<<<< HEAD
#   <bold><yellow>Welcome to LBRYQuest, the server that runs on LBRY Credits! ^_^<reset>
=======
#   <bold><yellow>Welcome to LBRY Quest, the server that runs on LBRY Credits! ^_^<reset>
>>>>>>> master
#
#   <green>Your bank balance is: <walletAmount>
