superuser: null
# commented until <walletAmount> gets a class getter
#welcomeMessage:
#   <bold><yellow>Welcome to LBRY Quest, the server that runs on LBRY Credits! ^_^<reset>
#
#   <green>Your bank balance is: <walletAmount>
